# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mngapi:
    image: mngapi
    build:
      context: .
      dockerfile: Mng.Api/Dockerfile
    ports:
      - 80:80
      - 443:443
